{
 "title": "Product API",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Kafka producer metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total sent events per topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(topic) (changes(kafka_event_sent_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total failed to send events per topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(topic) (changes(kafka_event_sent_failedl[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kafka consumer metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total incoming events per topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(topic) (changes(kafka_event_received_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total processed events per topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(topic) (changes(kafka_event_processed_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total consumer lag per topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_event_sent_total - kafka_event_processed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total failed to process events per topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(topic) (changes(kafka_event_process_failed_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}